### ISSUE TITLE
More room for 30 mm rods in XX joints

### ISSUE THREAD

**Issue by Kruppes** [VoronDesign/Voron-Afterburner#3] opened 2020-02-06 18:39 UTC
With a 30,0 mm rod being perfectly flush with the bottom bearing it sticks out of the top bearing ~1mm. This makes the rod touch the printed part and block the rotation once fully assembled. Since the pulley is glued into place it can not be corrected easily after assembly and finding out. 

 Can you reduce a little more material above to give room for non perfect alignment or add the ideal position of the pulley (in mm length of the rod sticking out on each side).

**Comment by FHeilmann** [comment] 2020-10-15 07:49
Since Afterburner has since left the beta stage (I assume this issue pertains to the beta release) I'm going to close this issue, if the issue is still present on the release version, feel free to reopen it!

-Florian

**Closed by FHeilmann** 2020-10-15 07:49 UTC
