### ISSUE TITLE
Inconsistent extrusion / Z Banding

### ISSUE THREAD

**Issue by Roycinger** [VoronDesign/Voron-Afterburner#6] opened 2021-01-02 14:50 UTC
Hi,
first and foremost I would like to bring this issue to attention where we can track it all together properly. Discord doesn't seem the right place for me as messages and focused discussions get overscrolled and interrupted with non-related topics very quickly.
Before I start I want to mention that I don't expect this issue to get solved by the Voron Team alone. Moreover, I want to evaluate this together with you so that the entire Voron community can benefit from it.

I started facing this extrusion issue when I completed my 100%-built-by-specc Switchwire. In the beginning I was thinking that the printer wasn't properly tuned yet. So I went through all the tuning steps (aligning belts, rails, tuning for filament, E-steps, run_current etc). The result didn't improve within about 90 or more test prints (where I tested every single extrusion related slicer and firmware setting).
Over the course of a few weeks, I partly reassembled the SW again, paying special attention for accuracy, squareness, etc, results didn't improve. At this point I was still under the impression that the issue was on my side as the issue still persists.
To rule out the AB, I converted my SW to bowden and the issue was gone! So I came to the conclusion that there might be a problem with the AB itself.
Because of that, I reprinted the Clockwork parts, changed the TL gears, changed all bearings, changed the motor, changed the entire hotend, precisely cut the PTFE tube. No change in results at all. 
For informational purposes, this is my config: https://pastebin.com/nyULd4ca
Fast forward:
Up to yesterday, I noticed that more and more people are facing the same or similar issues, even if they might be fine with the results.
I got sent a plethora of pictures which I was allowed to use in this Git issue. They all more or less show the same problem,
Please note that most pictures where shot with "bad" light, directly from the top to make the issue apparent.
These are kinda mixed from specc-built v2.4's and SW's.
![image](https://user-images.githubusercontent.com/7791335/103459298-959e6a00-4d0e-11eb-8ae3-d0e621562291.png)
![image](https://user-images.githubusercontent.com/7791335/103459302-a18a2c00-4d0e-11eb-8b4a-8f5d0f127569.png)
![image](https://user-images.githubusercontent.com/7791335/103459326-dac29c00-4d0e-11eb-98cb-b90ad9a46360.png)
Cubes from my SW:
![image](https://user-images.githubusercontent.com/7791335/103459331-e4e49a80-4d0e-11eb-9482-01a9c88617f1.png)
![image](https://user-images.githubusercontent.com/7791335/103459362-2f661700-4d0f-11eb-82c5-4110f879b18a.png)
Random v0 part printed with my SW:
![image](https://user-images.githubusercontent.com/7791335/103459403-794efd00-4d0f-11eb-9a82-27f32ccd3424.png)
Another set of v0 parts:
![image](https://user-images.githubusercontent.com/7791335/103467952-88a46980-4d54-11eb-8357-13a0780cd9d2.png)

For my part, I could rule out any looseness in the kinematics or topics related to filament (as I made tests with PETG, PLA and ABS from various brands). 
Those defects appear either random (not at fixed heights) or depending on print features within the model (plateaus, holes, etc).
 
For me it comes down to a few points:
- requirement of quality is not the same for every user (they might live with the defects)
- There might be issues with either the AB internat geometry or the ABS shrinkage bothering with the tolerances
- related to the point above: A genuine Bondtech BMG in a direct drive situation in another (non Voron) printer works perfectly without showing these defects
- Using a bowden extruder (M4 in this case) eliminated the issue

Yesterday, I had a brief conversation with Ray. I introduced the topic "Prusa Issue 602", which looks awefully similar to this. 
I would be happy if you could either assist with this issue or shed some light on it. 

Thanks in advance!

**Comment by toskium** [comment] 2021-01-02 14:53
Thank you for submitting this issue. I do experience the same results and I was not yet able to pin down the root cause of it.

**Comment by toskium** [comment] 2021-01-02 19:34
To add something to the issue. I was doing input shaper calibration and the outcome of the calibration print is imho interesting.

Since klipper calculates the extruder acceleration according to the xy acceleration the striping pattern changed accordingly.

See the attached picture.
![PXL_20210102_192655708.jpg](https://user-images.githubusercontent.com/15872792/103465213-d1025e00-4d39-11eb-9583-d16992ee0e95.jpg)

It appears more or less intense starting from acceleration 1250 all the way up to 7500.

**Comment by BladeScraper-Designs** [comment] 2021-01-02 20:32
Same here as well.  tried new BMG parts, various flow settings, various accels and speeds from 30mm/s and 500acc to 120mm/s and 5k accel, etc.

![20201230_090949](https://user-images.githubusercontent.com/40482965/103466074-2c672880-4d07-11eb-8f90-c7c5e7c46068.jpg)
![20201230_090944](https://user-images.githubusercontent.com/40482965/103466076-2cffbf00-4d07-11eb-852a-62bf8d07452f.jpg)

**Comment by Gizzzle** [comment] 2021-01-02 22:15
Can confirm the issue.
![IMG_20210101_203721](https://user-images.githubusercontent.com/49840050/103467537-542eae80-4d50-11eb-9566-dbac69fd50c6.jpg)
![IMG_20210101_203728](https://user-images.githubusercontent.com/49840050/103467539-555fdb80-4d50-11eb-9734-d4066ef9a8ff.jpg)

**Comment by mgrl** [comment] 2021-01-02 22:24
Just built a v1.8 with bowden. I think I don't see the effect, which aligns to your proposal, right?

![IMG_20210102_231841280](https://user-images.githubusercontent.com/3868450/103467637-5cd3b480-4d51-11eb-81b9-30c1ebb07c7d.jpg)
![IMG_20210102_231749998](https://user-images.githubusercontent.com/3868450/103467638-5e9d7800-4d51-11eb-9d51-904a890bddb0.jpg)
![IMG_20210102_202726457](https://user-images.githubusercontent.com/3868450/103467639-60673b80-4d51-11eb-95dd-95150e8eccad.jpg)

**Comment by toskium** [comment] 2021-01-02 22:29
> Just built a v1.8 with bowden. I think I don't see the effect, which aligns to your proposal, right?

Yes, correct. The issue seems to be exclusive to the clockwork extruder. Your input is much appreciated!

**Comment by Serpreme** [comment] 2021-01-03 00:48
Can we make a list of the items that are used and not used between the bowden and direct drive? The gears, motors, wiring, and then we can slowly eliminate those items. We can try to test for things like EMI for example

**Comment by Gizzzle** [comment] 2021-01-03 00:59
> Can we make a list of the items that are used and not used between the bowden and direct drive? The gears, motors, wiring, and then we can slowly eliminate those items. We can try to test for things like EMI for example

I can eliminate every part on the Afterburner except the hotend, but that's not the problem since the other guys are using a dragon while I'm using a v6. Also EMI is not the issue since I used another motor without cable management which lead to the cable not crossing another cable in it's way to the board.
Stepper driver was also swapped from a LV8729 to a TMC2209

**Comment by BladeScraper-Designs** [comment] 2021-01-03 02:55
Added details to my post.

**Comment by jdlongenecker** [comment] 2021-01-03 03:03
Hello everyone, I have a recommendation to make. 

In order make a proper comparison, I recommend that someone mount a BMG extruder directly to Afterburner in place of the Clockwork module. If the issue clears up, then you can root cause the issue to be something with the clockwork module itself. If the issue persists, then the source of the issue is something else.

I would not compare a bowden and direct drive mount of the same extruder--the physics of printing through a long tube with springy filament is different than when the extruder is right on top of the hotend.

**Comment by Gizzzle** [comment] 2021-01-03 09:39
> Hello everyone, I have a recommendation to make.
> 
> In order make a proper comparison, I recommend that someone mount a BMG extruder directly to Afterburner in place of the Clockwork module. If the issue clears up, then you can root cause the issue to be something with the clockwork module itself. If the issue persists, then the source of the issue is something else.
> 
> I would not compare a bowden and direct drive mount of the same extruder--the physics of printing through a long tube with springy filament is different than when the extruder is right on top of the hotend.

We had the idea too, but that's nearly impossible because of the small footprint of the afterburner.

**Comment by JayAwesome87** [comment] 2021-01-03 14:21
Same problem since day one. I'm using a Galileo Clockwork now and the problem still persists.

![20210103_142033](https://user-images.githubusercontent.com/63011473/103480842-10cb5300-4dd7-11eb-9569-18f49e91597f.jpg)

**Comment by Roycinger** [comment] 2021-01-03 14:46
> In order make a proper comparison, I recommend that someone mount a BMG extruder directly to Afterburner in place of the Clockwork module. If the issue clears up, then you can root cause the issue to be something with the clockwork module itself. If the issue persists, then the source of the issue is something else.

This is easier said than done because of a few points:
- The BMG is 2.6mm thicker than the Clockwork:
![image](https://user-images.githubusercontent.com/7791335/103481343-ab796100-4dda-11eb-96da-95eabd3ed62b.png)
- The filament path is not the same as the Clockwork's:
![image](https://user-images.githubusercontent.com/7791335/103481353-bdf39a80-4dda-11eb-9275-6bc29c552557.png)

All in all, almost every single part of the AB would have to be redrawn to accomodate a BMG

**Comment by jdlongenecker** [comment] 2021-01-03 15:04
> Same problem since day one. I'm using a Galileo Clockwork now and the problem still persists.
> 
> ![20210103_142033](https://user-images.githubusercontent.com/63011473/103480842-10cb5300-4dd7-11eb-9569-18f49e91597f.jpg)

Is this the version with planetary gears? If so, this would imply that it's not the Clockwork module itself but something else :)

**Comment by Gizzzle** [comment] 2021-01-03 15:12
I'm using my Ender Switchwire Conversion

**Comment by jdlongenecker** [comment] 2021-01-03 15:14
> > In order make a proper comparison, I recommend that someone mount a BMG extruder directly to Afterburner in place of the Clockwork module. If the issue clears up, then you can root cause the issue to be something with the clockwork module itself. If the issue persists, then the source of the issue is something else.
> 
> This is easier said than done because of a few points:
> 
> * The BMG is 2.6mm thicker than the Clockwork:
> * The filament path is not the same as the Clockwork's:6bc29c552557.png)
> 
> All in all, almost every single part of the AB would have to be redrawn to accomodate a BMG

Let me see what I can do, I would like to support your testing! I do not have time right now for diagnosing the issue but I may be able to provide some parts you can print with to test the theory.

**Comment by JayAwesome87** [comment] 2021-01-03 15:16
> > Same problem since day one. I'm using a Galileo Clockwork now and the problem still persists.
> 
> Is this the version with planetary gears? If so, this would imply that it's not the Clockwork module itself but something else :) since there are no shared parts between the Galileo Clockwork (planetary) and the standard Clockwork BMG version.
> 
> Also, can we make sure to document which printer these examples are from? That would be helpful in the root cause!

Yep, the one with planetary gears. Printed on a Voron 2.4 250.

**Comment by jdlongenecker** [comment] 2021-01-03 15:25
<img width="314" alt="Screen Shot 2021-01-03 at 10 24 31 AM" src="https://user-images.githubusercontent.com/11861478/103482267-ea44f200-4dad-11eb-87dc-ca787a3fd1ce.png">
<img width="514" alt="Screen Shot 2021-01-03 at 10 24 25 AM" src="https://user-images.githubusercontent.com/11861478/103482268-eb761f00-4dad-11eb-8ec7-c936d961977d.png">

I am thinking something simple like this--no part cooling, but it should still show improvement

**Comment by Gizzzle** [comment] 2021-01-03 15:26
I indeed worked on a solution like this. Need to wait until my V0 is ready again to print the parts...

![grafik](https://user-images.githubusercontent.com/49840050/103482291-5f311f80-4de0-11eb-933c-cbcd8a6341e6.png)

**Comment by jdlongenecker** [comment] 2021-01-03 15:27
that looks good! I think it will work for testing 👍

**Comment by herexx6349** [comment] 2021-01-03 21:05
same issue hier with a brand new 2.4 with AB

![IMG_20210103_205426](https://user-images.githubusercontent.com/65120178/103488747-b3072d00-4e0f-11eb-9ec2-9413808c47d9.jpg)
![IMG_20210103_205533](https://user-images.githubusercontent.com/65120178/103488750-b8647780-4e0f-11eb-9757-9b133519fa1b.jpg)

**Comment by herexx6349** [comment] 2021-01-03 22:21
took some photos under a microscope, looks like a x/y wobble^^
![2](https://user-images.githubusercontent.com/65120178/103490179-64ab5b80-4e1a-11eb-8151-421502406d0c.jpg)
![3](https://user-images.githubusercontent.com/65120178/103490181-6543f200-4e1a-11eb-81c0-21f23a0cbd05.jpg)
![4](https://user-images.githubusercontent.com/65120178/103490182-65dc8880-4e1a-11eb-9c43-5067818f9de9.jpg)
![Unbenannt](https://user-images.githubusercontent.com/65120178/103490184-65dc8880-4e1a-11eb-9507-97f16038086e.png)

**Comment by Gizzzle** [comment] 2021-01-04 12:37
Update: Adding the complete BMG didn't make a difference. So there must be a problem in something that the Switchwire and the V1/V2 have in common.

**Comment by maximm07** [comment] 2021-01-04 19:39
Just for my curiosity, my 2.4 voron is in final build stage so i will be able to test myself soon..is the issue appearing with all hot ends? dragon, V6 and mosquito? is it the same with any of the mods optimised for cooling (5015 variants)? current hotend cooling for dragon is not the best, for V6 it should be ok tough.

**Comment by Roycinger** [comment] 2021-01-04 20:45
> Just for my curiosity, my 2.4 voron is in final build stage so i will be able to test myself soon..is the issue appearing with all hot ends? dragon, V6 and mosquito? is it the same with any of the mods optimised for cooling (5015 variants)? current hotend cooling for dragon is not the best, for V6 it should be ok tough.

Afaik it happens across all hotends. I'm not too sure about the Mosquito as very few people are actually using it.





> Update: Adding the complete BMG didn't make a difference. So there must be a problem in something that the Switchwire and the V1/V2 have in common.

Please note that a BMG Clone was used by Gizzle for the test. 
In my initial post I was speaking of a genuine Bondtech BMG.

**Comment by jtrmal** [comment] 2021-01-04 22:19
@Roycinger how about trying "git bisect"? I'm in my post-construction afterglow and I don't have a good idea how my prints should/could look like, but bisecting might help you

**Comment by Roycinger** [comment] 2021-01-04 22:40
@jtrmal I dont see how a git bisect could help with this issue. Could you please elaborate?

**Comment by jtrmal** [comment] 2021-01-04 22:43
hm, I was thinking if you could pinpoint some working (i.e. producing nice prints) revision and using the current as "bad", you could (perhaps) manage to track down which commit has introduced this deterioration?

**Comment by jtrmal** [comment] 2021-01-04 22:46
but I just noticed there is an implied fact these are all new machines? In that case bisect wouldn't help, I think, yeah....

**Comment by fkotey** [comment] 2021-01-04 23:55
I have BLV MGN Cube and Ender 3 with the same issue as well. Currently, I am working on tuning my printers to print parts for a Voron Switchwire but this issue is preventing from doing that. The common thing between my BLV MGN Cube and the Ender 3 Linear Rail. I have been investigating this issue for months now and I believe it lies with the cheap linear rails (bought from Blurolls) I am using. 

I will confirm my assumption in a few weeks time as I have ordered genuine Hiwin linear rails to upgrade my printers. My Ender 3 with wheels never had this problem.

**Comment by Roycinger** [comment] 2021-01-05 09:29
As a general plea:
If you're experiencing a similar issue, please make sure it's really related to this issue.
Though it might look similar, the root cause can be vastly different.
The issue for me and @Gizzzle was solved by converting to bowden, so we can eliminate rails from as the root cause.
Rather, this strongly points to some aspect in the Afterburner

**Comment by jdlongenecker** [comment] 2021-01-05 14:19
Note there will always be some inconsistency like this--we can probably get a bit better to a certain extent but at harsh lighting angles there will always be some surface imperfection. Some reading that may be helpful is at this link (scroll down to the "inconsistent extrusion" section:

https://blog.prusaprinters.org/prusa-research-summer-update-2018_8535/

I still stand by my theory that bowden tend to not have this issue as much as direct drive (any direct drive) will. Any slight variation in the drive gears, filament thickness, etc--will directly translate into an almost 1:1 change in how much filament is pushed through the nozzle with a direct drive extruder. On a bowden extruder, all of those inconsistencies are dampened by the "spring" of filament through the bowden tube and the majority of that variation is smoothed out. Of course--bowden comes with other complications and downsides, but that's for another discussion 👍 

I think the part we are missing @Roycinger is a print on your Voron with a genuine BMG attached to the toolhead, similar to some of the issues above? If that resolves the issue we can point to Clockwork (or maybe the clone BMG gears), if it does not, then we know the issue is something else.

**Comment by Roycinger** [comment] 2021-01-05 14:27
@toskium thanks for uploading these detailed pics. It helps narrowing down the issue.
@jdlongenecker You are certainly right with the "filament as a spring" argument that smoothes out such imperfections.
Unfortunately, I don't have a genuine BMG attached to my printer. The examples with that genuine BMG I was talking about were from another (non Voron) printer that I already sold. I can cram out some example pics though sor sure.
For your edit: I have genuine Bondtech components on the way, along with SLS printed Clockwork parts. This way we can potentially eliminate 2 parts in the equation:
- genuine Bondtech gears vs. TL (or whatever brand) clone gears
- ABS / shrinking being the culprit.

I will keep you updated as soon as the parts get in.

**Comment by raymondh2** [comment] 2021-01-05 16:26
I run all genuine Bondtech parts in my Afterburner. While changing two variables (clockwork > BMG and TL guts to > Bondtech guts) might give insight I am highly doubtful in this. From what I have seen even the bowden M4 suffers from this too a degree.

**Comment by ctilley83** [comment] 2021-01-08 17:15
To me this looks like classic over extrusion. Probably by 3-5%.  Dial it back extrudermeister

**Comment by hhammarstrand** [comment] 2021-01-08 17:27
> To me this looks like classic over extrusion. Probably by 3-5%.  Dial it back extrudermeister

Mine is actually calibrated in superslicer. I can try lowering and posting the results later on, my v2 is currently undergoing maintainace

**Comment by hhammarstrand** [comment] 2021-01-09 21:20
![image](https://user-images.githubusercontent.com/61510000/104108842-7d0ef080-52c8-11eb-9e98-093f861b23f0.jpeg)

Printed with my switchwire on 0.95 extrusion multiplier. My calibrated value is 1.03. 

Specs: 
Switchwire 
Bondtech gears 
Genuine v6, 0.4 nozzle 
LDO extruder motor

**Comment by Roycinger** [comment] 2021-01-09 21:54
Update from the initial post.
Re-aligned Z-Rails once again and re-did the belts.
![IMG_2376](https://user-images.githubusercontent.com/7791335/104109379-7d5dba80-52cd-11eb-88bd-3fe6be196485.jpeg)
![IMG_2375](https://user-images.githubusercontent.com/7791335/104109380-7df65100-52cd-11eb-885e-89cc39e525da.jpeg)
![IMG_2374](https://user-images.githubusercontent.com/7791335/104109381-7f277e00-52cd-11eb-9ae7-1eaaba53a20d.jpeg)
![IMG_2377](https://user-images.githubusercontent.com/7791335/104109382-7fc01480-52cd-11eb-92c9-1671f7aa9b72.jpeg)

Didn't upgrade to the genuine BMG gears yet as I'm still waiting for the SLS parts to be delivered

**Comment by ctilley83** [comment] 2021-01-09 21:57
> ![image](https://user-images.githubusercontent.com/61510000/104108842-7d0ef080-52c8-11eb-9e98-093f861b23f0.jpeg)
> 
> Printed with my switchwire on 0.95 extrusion multiplier. My calibrated value is 1.03.
> 
> Specs:
> Switchwire
> Bondtech gears
> Genuine v6, 0.4 nozzle
> LDO extruder motor

Looks a lot better.  Now just tune pressure advance and you should be good to go. I don’t trust calibrating using a 1 wall cube. Calipers aren’t accurate enough. What slicer are you using?

**Comment by hhammarstrand** [comment] 2021-01-09 22:02
> > ![image](https://user-images.githubusercontent.com/61510000/104108842-7d0ef080-52c8-11eb-9e98-093f861b23f0.jpeg)
> > Printed with my switchwire on 0.95 extrusion multiplier. My calibrated value is 1.03.
> > Specs:
> > Switchwire
> > Bondtech gears
> > Genuine v6, 0.4 nozzle
> > LDO extruder motor
> 
> Looks a lot better. Now just tune pressure advance and you should be good to go. I don’t trust calibrating using a 1 wall cube. Calipers aren’t accurate enough. What slicer are you using?

Thanks for the input, but it's actually looking much worse overall. I'm using superslicer 2.2.53. Used superslicers built in calibration to do the extrusion multiplier tuning, not the "one wall cube".

**Comment by 9ary** [comment] 2021-01-11 20:10
I haven't done enough testing on my SW to know if I'm affected yet, but I'd still like to pitch in because I find this issue interesting.
Just throwing some ideas at the wall here but some things I've noticed when building which might be worth investigating:
- The E motor shaft touches the filament above the hob gears, while it sounds unlikely there might be some sort of interaction there.
- The shaft the reduction gear and drive side hob gear are mounted to is supported axially by the motor faceplate and the wall in the extruder body. Ideally there should be a little bit of axial play or we could be facing unwanted drag. On the other hand, too much axial play there might cause the reduction gear to rub against the extruder body, and back and forth movement might actually explain why we're seeing inconsistency throughout the print. Really, the only parts of this assembly that should ever touch stationary bits are the outer bearing races. I also need to confirm whether one of the bearing can touch the hob gear or not.

The above points have caught my attention because the motor I was planning to use turned out to have an extra long shaft that's not compatible with the clockwork (it blocks the filament path), so I had to space it out. The reduction/drive side gear assembly has a lot of axial play because of that. I've noticed significant drag (more than expected) and possibly grinding while pulling filament through the extruder with the hotend removed. I've already got a new motor on the way and I'll report back as soon as it's installed.

My extruder internals and the motor in question are known good, I've used them to print all of my switchwire parts on my ender 3 and I haven't noticed anything like what you all are facing. They were part of TL's AL-BMG-AIR extruder kit.

**Comment by rcfishhunt** [comment] 2021-01-12 01:05
One issue that I did notice was the driven shaft slides side to side in the afterburner.   Mine has similar defects.   The gears are tl labs hotend pheatus dragon v1
![Uploading 20210111_190352.jpg…]()

**Comment by hhammarstrand** [comment] 2021-01-12 05:52
> One issue that I did notice was the driven shaft slides side to side in the afterburner. Mine has similar defects. The gears are tl labs hotend pheatus dragon v1

I noticed too. I used shims to remove the side to side movement and get the filament path spot on. Not sure if this has any real benefit, I guess the gears "auto align" when you put filament in.

**Comment by 9ary** [comment] 2021-01-12 05:55
If you mean the idler, it's indeed supposed to self align when the filament is in. That's how it is in a stock BMG body too.

**Comment by hhammarstrand** [comment] 2021-01-12 05:59
> If you mean the idler, it's indeed supposed to self align when the filament is in. That's how it is in a stock BMG body too.

I was referring to the shaft assembly. The idler didn't have nearly as much play as the shaft assembly
![image](https://user-images.githubusercontent.com/61510000/104275613-79839100-54a3-11eb-832f-6105710ecb28.png)

**Comment by 9ary** [comment] 2021-01-12 06:03
Alright, this might be worth looking into then, because it really needs to be constrained properly.

**Comment by ctilley83** [comment] 2021-01-23 14:55
Seems my afterburner is not affected.  You didn’t cut your ptfe tube too long did you? There was an issue on the prusa forums that if the ptfe tube gets compressed during assembly, it can lead to similar extrusion issues. The particular issue was with a prusa mini which has a similar geared setup to the afterburner. Seems that after properly trimming the ptfe tube, the issue disappeared.

**Comment by ctilley83** [comment] 2021-01-23 14:57
![573C7DF1-912F-4B43-A624-D35B37F7418A](https://user-images.githubusercontent.com/746467/105595145-5ab5b200-5d61-11eb-9c56-44ea75fd9a7e.jpeg)

that’s the worst downlighting I could get.  Extrusion seems pretty spot on.  Only a few inconsistent spots around features

**Comment by rcfishhunt** [comment] 2021-01-23 15:40
I am not really sure.  I had to guess my length.   For the ptfe

**Comment by JustinCaseOfWolf** [comment] 2021-01-23 15:54
> I am not really sure. I had to guess my length. For the ptfe

i have cut the afterbuner top in half so i can measure exactly the ptfe length. not quite the fastest / cheapest way to do it but i know for sure it is the correct lenght. so in my case that does not apply

**Comment by JustinCaseOfWolf** [comment] 2021-01-23 15:55
@ctilley83 different colours shows different surface. while yours is less obvious than the black above i am sure with the right light your can be made more visible.

**Comment by rcfishhunt** [comment] 2021-01-26 23:47
I am making some progress with this.  And it might seem simple.   The build instructions say nothing about using the nylon washer on the thumb screw from the bmg parts.  I took mine off and replaced it with a thin flat washer to keep the spring from digging in to my printed parts and was able to reduce spring tension and it is making an amazing difference.   Still loosening to get the best results.   But her is with and without the nylon spacer
![Uploading 20210126_174702.jpg…]()

**Comment by Gizzzle** [comment] 2021-01-27 00:27
> I am making some progress with this. And it might seem simple. The build instructions say nothing about using the nylon washer on the thumb screw from the bmg parts. I took mine off and replaced it with a thin flat washer to keep the spring from digging in to my printed parts and was able to reduce spring tension and it is making an amazing difference. Still loosening to get the best results. But her is with and without the nylon spacer
> Uploading 20210126_174702.jpg…

Unfortunately I can't see your pictures, but I have used the washer from the beginning and my print quality was bad. So maybe it's only a coincidence in your case.

**Comment by rcfishhunt** [comment] 2021-01-27 00:42
Ok I will try to reload them

**Comment by ehellman** [comment] 2021-02-04 23:14
I have followed this discussion for a while and sadly haven't been able to chip in because I am still waiting for my POWGE package which contains all my pulleys etc.

Have printed the entire AB though, inspected, measured, tried V6 and Dragon variants. While I do have some ideas, first I would like a question answered, if anyone has time:

We see a bunch of calibration cubes here, great. But could someone take the time to create a vase mode print and post it here? Doesn't have to be a super advanced vase. I usually print a 100x30x120 (x, y, z) rectangle in vase mode to make some basic tests. Then I switch over to one of the widely available vase models, but the simplest ones are the ones that could show you the biggest effects. It should have some shapes, but not go overboard with it. Would be an interesting test at least.

**Comment by mateuszbrzezinski** [comment] 2021-02-05 13:25
I'm experiencing same issue, V2.4 with AB-BN-25 cooling
But how bad it looks it depends at what angle you look at and if the light is harsh or not.

![image](https://user-images.githubusercontent.com/1177739/107039210-dda52680-67bd-11eb-9577-20921225db33.png)

**Comment by mateuszbrzezinski** [comment] 2021-02-05 15:01
What if that is some bug in Klipper? SKR? TMC2209?
Anyone using Duet to compare this?

**Comment by 9ary** [comment] 2021-02-05 15:13
I've rebuilt my extruder with my new motor, and I'm not affected apparently. I'm using Klipper on a Duet 2 WiFi (TMC2660), nothing is tuned yet.

**Comment by mateuszbrzezinski** [comment] 2021-02-06 17:47
I was printing test cilinders, so there is no any sharp angles, so to exclude such variable. Then that is interesting, when nozzle crosses Y center axis of model, so before crossing this one of the AB drivers is rotating faster, then after crossing the other motor is rotating faster, then funny things happens, I marked point when that happens. So as you can see, on the left of that mark the issues are more visible, then suddenly after crossing the mark, on the right hand side, issues are much less visible, or almost not visible.
![20210206_182626](https://user-images.githubusercontent.com/1177739/107125641-6ea5fb80-68ab-11eb-9863-7558423008d0.jpg)
![Uploading 20210206_182619.jpg…]()

Maybe that is something with motor synchronisation?

**Comment by mateuszbrzezinski** [comment] 2021-02-07 11:00
Another experiment:
Printed 2 cubes like that:
![image](https://user-images.githubusercontent.com/1177739/107144448-8331d480-693b-11eb-9f3d-f45c0effd460.png)
You can see the difference.

Part printed at 90* angle front side:
![image](https://user-images.githubusercontent.com/1177739/107144473-abb9ce80-693b-11eb-80bc-9ae57ea38e43.png)


Part printed at 45* angle:
![image](https://user-images.githubusercontent.com/1177739/107144498-ca1fca00-693b-11eb-8f05-58f6ded8f4cb.png)


But other interesting thing is part 90* but wall on Y axis are fine:
![image](https://user-images.githubusercontent.com/1177739/107144519-ee7ba680-693b-11eb-8463-05357fcb32d6.png)


What the hell?

**Comment by 9ary** [comment] 2021-02-07 11:05
Interesting results, and puzzling considering bowden extruders appear to solve the problem for others, maybe you're facing a different issue? I also recall that vase mode prints didn't have any problems, but you do.

**Comment by mateuszbrzezinski** [comment] 2021-02-07 12:44
@9ary no that are not vase mode prints, that are 30x30x15 cubes, 4 perimeters.

**Comment by 9ary** [comment] 2021-02-07 12:54
The cylinders too?

**Comment by mateuszbrzezinski** [comment] 2021-02-07 13:46
@9ary cylinders led me to printing 45* cubes, but anyway cylinders that is another 15 minutes print, so why not :)

**Comment by 9ary** [comment] 2021-02-07 13:48
I was asking whether the cylinders were vase mode prints, but it looks like they're not.

**Comment by Sureiya** [comment] 2021-02-15 05:01
I'm getting very similar artifacts in my newly built switchwire. For reference I'm using an MKS Robin Nano 2.0 with external 2209 drivers. The only reason I'm posting here so soon is that I noticed the shaft assembly pictures. I couldn't get the set screw out of the BMG clone's shaft, so I was not able to reposition the extruder gear on the shaft assembly and believe this is what is causing my problem, as the alignment seems off. If anyone has any tips for getting this really crappy set gear out I can test.

**Comment by jurisv** [comment] 2021-02-15 18:55
Same here. Reference build with AB and print size 350mm. TMC2209 drivers. When printing PC it was less obvious, now with quality ABS filament from KVP having the same vertical banding issue.

**Comment by fabe83** [comment] 2021-02-18 11:45
I am using a Voron 2.4 250 with Afterburner (Direct Drive). For this I used Orgnial BMG components. 2x SKR 1.3 + TMC 2209 driver.
I have the same artifacts on my prints. I made various test prints, depending on the extrusion multiplier, the artifacts get worse.
I have calibrated everything as well as I can. Input Shaper and Pressure Advance seem to have only a minor influence.
I've already completely re-printed the afterburner, replaced all mechanical components, the hotend, and I'm still waiting for new steppers to test them.

**Comment by perikanttila** [comment] 2021-02-19 09:15
I can confirm i have the same issue and it dissappears in bowden setup. I do have my own metal corexy printer, no play in any means. What I am going to do is make sure that the 40mm Bowden tube is not pressed down, and will also support it inside heat sink (e3d) so that it can not wiggle. I will report here of my findings.

**Comment by perikanttila** [comment] 2021-02-19 19:30
No difference what so ever.

**Comment by raymondh2** [comment] 2021-02-19 20:38
This is an issue that is not isolated purely to Voron printers. Given the broad reaching impact beyond just this community, we are closing this issue until a solution is able to be determined for the betterment of the 3D printing community as a whole.

**Closed by raymondh2** 2021-02-19 20:38 UTC

**Comment by perikanttila** [comment] 2021-02-19 21:30
Wow head in sand

**Comment by Gizzzle** [comment] 2021-02-19 21:50
> This is an issue that is not isolated purely to Voron printers. Given the broad reaching impact beyond just this community, we are closing this issue until a solution is able to be determined for the betterment of the 3D printing community as a whole.

Well, this is not the reaction of the voron devs I expected. It's clearly a Clockwork related issue which only the Voron CoreXY and CoreXZ printers had. Because of this I expected atleast a public message at the discord channel which informs the whole community about the problem and confirms that you work on a solution!

**Comment by JustinCaseOfWolf** [comment] 2021-02-19 21:56
@raymondh2 there are plenty of printers that do not have this issue. for a top printer voron should be printing top and this issue is not present in ender for example which costs a fraction of a voron.

**Comment by herexx6349** [comment] 2021-02-19 21:59
I can only agree with this. When you enter voron discord, you get the impression that you have joined an elite community. A community that positions itself so highly that other products and solutions are often dragged through the mud and ridiculed. Most of the pictures in the showcase were taken in a light where the problems are not visible, which led me to build this "perfect" printer. The fact that the problems exist has been ignored for two months and none of the dev's have commented on the problem. Also, there are no pinned messages warning newcomers about possible problems...

**Comment by federico-galli** [comment] 2021-02-19 22:13
> This is an issue that is not isolated purely to Voron printers. Given the broad reaching impact beyond just this community, we are closing this issue until a solution is able to be determined for the betterment of the 3D printing community as a whole.

Can you give any reference to this? In this thread every post is about an Afterburner setup. If other people using the Afterburner on 3d printers others than Voron are facing the issue this could be an Afterburner issue. Perhaps who is not facing this problem could share his Afterburner setup so that is possible to debug

**Comment by FHeilmann** [comment] 2021-08-13 13:35
This issue was closed and locked 6 months ago for the following reasons:
- Issue 6 is not specific to the Voron Afterburner, it also isn't specific to VoronDesign printers and therefore this repository was deemed a suboptimal venue for discussing, analyzing and solving it.
- The identification of the issue itself and possible solutions was diluted by the following factors:
  - Non-standard or modded printers
  - Other extrusion or tuning-related issues
  - Non-standard identification methodology.
- As a result a lot of the discussion got derailed to "is it issue 6 or is it something else" and "is it my modded extruder or is it something else" . 

That said, we do not believe that issue 6 doesn't exist or that it definitely can't be solved. Given the nature of the issue, though, a lot of strict testing parameters and careful investigation are required. We continue to investigate this issue internally, striving to create such a strict and stable set of testing parameters to reliably identify the source of this issue and possible solutions (if they exist).
