### ISSUE TITLE
[Beta-1] make the latch thicker

### ISSUE THREAD

**Issue by schlnk** [VoronDesign/Voron-Afterburner#1] opened 2020-02-03 18:27 UTC
The latch is too weak at its thinnest part and prone to bending (see the pic, upper one) I propose to make it thicker (see the pic, lower one). Discord discussion is [here](https://discordapp.com/channels/460117602945990666/658599429422448671/673165851893170197).
![IMG_20200201_164735](https://user-images.githubusercontent.com/34524772/73679479-814f8880-46cb-11ea-8577-e726869bab8e.jpg)

**Comment by FHeilmann** [comment] 2020-10-15 07:48
Since Afterburner has since left the beta stage I'm going to close this issue, if the issue is still present on the release version, feel free to reopen it!

-Florian

**Closed by FHeilmann** 2020-10-15 07:48 UTC
