### ISSUE TITLE
[Beta-1] make the boss fit a bit looser on the extruder_body

### ISSUE THREAD

**Issue by schlnk** [VoronDesign/Voron-Afterburner#2] opened 2020-02-03 18:38 UTC
Probably the fit for the small boss on the extruder body is too tight. Was unable to disassemble  without breaking it. Discord discussion is [here](https://discordapp.com/channels/460117602945990666/658599429422448671/665984352265699329).

![image](https://user-images.githubusercontent.com/34524772/73680485-6251f600-46cd-11ea-99b0-2d9cca0a75a7.png)

**Comment by FHeilmann** [comment] 2020-10-15 07:48
Since Afterburner has since left the beta stage I'm going to close this issue, if the issue is still present on the release version, feel free to reopen it!

-Florian

**Closed by FHeilmann** 2020-10-15 07:48 UTC
