### ISSUE TITLE
Phaetus BMO part cooling ducts are too high

### ISSUE THREAD

**Issue by Krieselwind** [VoronDesign/Voron-Afterburner#33] opened 2021-12-28 20:01 UTC
distance between nozzle and highest point of fanduct is about 3mm.
![IMG_8603](https://user-images.githubusercontent.com/77192643/147602752-43d9206a-c063-4310-a0c1-22dde6872875.jpeg)
![IMG_8601](https://user-images.githubusercontent.com/77192643/147602770-d4daa02d-1326-4810-a15a-f58891a2c0ee.jpeg)

**Comment by raymondh2** [comment] 2021-12-28 20:12
Duplicate of #26

**Comment by Krieselwind** [comment] 2021-12-28 21:33
40.4mm

![IMG_8612](https://user-images.githubusercontent.com/77192643/147608601-b3d4364a-a46f-4833-a24b-e50feb9d2994.jpeg)

45.9mm
![IMG_8613](https://user-images.githubusercontent.com/77192643/147608645-6ea0da03-040c-4d62-95a4-a024e26022a8.jpeg)

11.6mm
![IMG_8614](https://user-images.githubusercontent.com/77192643/147608658-ed12051e-c50e-484a-a235-d5f16ccdc862.jpeg)

**Comment by raymondh2** [comment] 2021-12-28 22:49
Can you please check and make sure your screws aren't bottoming out.

**Comment by AaronHerrick** [comment] 2021-12-28 22:56
I can confirm that the BMO I used to test with is the same overall length.  I would guess that either the screws are bottoming out for you, or something else is preventing the hotend from seating fully.

**Comment by Krieselwind** [comment] 2021-12-29 07:32
Screws are tight. My second BMO was still in use and have the same size. 

Some more pictures from the hotend. ![image](https://user-images.githubusercontent.com/77192643/147638021-d89354e9-7dc2-40e4-a8ca-d4c194e26f7a.jpeg)![image](https://user-images.githubusercontent.com/77192643/147638022-ec4e8602-4fe5-4f24-ae9e-5d7679e7b0fa.jpeg)

**Comment by mathisschmieder** [comment] 2021-12-29 08:37
I can confirm both the measurements and the issue. While the 8mm M2.5 screws supplied with the hotend in fact do just bottom out on the heat sink, it is seated as far up as the printed part allows. Using 6mm M2.5 screws - while definitely preventing bottoming out -  leaves dangerously low thread engagement. 

Top of plastic part to the tip of the nozzle measures 61.6mm:
![IMG_1403](https://user-images.githubusercontent.com/951361/147642882-83772e0c-268e-4865-9dc8-97d300a51099.jpg)

**Comment by wile-e1** [comment] 2021-12-29 16:57
The nominal design height for the top of the toolhead to the base of the nozzle is 61.5mm for all hotends in Stealthburner, so you're pretty damn close at only being 0.1mm longer.

The airflow is aimed downward at the nozzle, not flat across the nozzle, so I think this may be more of a perception that the nozzle is too low.  My BMO looks exactly the same as yours and it's working ok, but I will admit that when the silicone sock goes on the heatblock, it looks like the airflow to the nozzle may be getting blocked slightly.

I think this warrants a little more investigation.  For now, I have revised the toolhead to reduce the possibility of the supplied fasteners being too long.

**Comment by AaronHerrick** [comment] 2021-12-31 01:59
the problem is me.  I've been saying the stickout should be 1.7mm, I was wrong. it should be what it is:  ~2.4mm

**Comment by raymondh2** [comment] 2022-01-07 18:40
@Krieselwind Can you please try the latest parts and let us know if that fixes the issue for you?

**Comment by Krieselwind** [comment] 2022-01-08 15:24
I see no difference?!

![image](https://user-images.githubusercontent.com/77192643/148649796-3de2f7a1-a95d-4843-8966-2a9ce07b42f2.jpeg)

**Comment by AaronHerrick** [comment] 2022-01-08 15:27
Please measure the distance as shown here: https://github.com/VoronDesign/Voron-Afterburner/issues/33#issuecomment-1002460699

**Comment by Krieselwind** [comment] 2022-01-08 15:31
61.7mm

**Comment by AaronHerrick** [comment] 2022-01-08 15:39
61.7 is fine.  The spec distance is 61.5mm.  different printers and plastics and measurements can account for that 0.2mm difference.

This mount is correct, the picture looks correct, and it should work correctly.  I made a mistake telling you that the stickout measurement should be 1.7mm.  the correct measurement for that should be around 2.4mm.  please refer to https://github.com/VoronDesign/Voron-Afterburner/issues/33#issuecomment-1003238959

It is better to measure from top of toolhead to nozzle (61.5mm)


I think we can close this issue now.

**Comment by Krieselwind** [comment] 2022-01-08 15:41
Ok, fine ☺️ thank you

**Closed as completed** 2022-01-11 15:11 UTC
Labels: resolved, waiting to close, stealthburner, hotends, beta
