### ISSUE TITLE
More clearance for PINDA probe (with Pinion adapter)

### ISSUE THREAD

**Issue by nife87** [VoronDesign/Voron-Afterburner#57] opened 2022-01-08 17:25 UTC
I would like to see more clearance for the PINDA probe (mine is a genuine SuperPINDA), using the Pinion adapter from v2.2.
It seems that the probe sits a bit lower (~1-2mm) on the SB than on the AB v2.4r1, so I had to adjust it to sit higher, but there was simply not enough clearance between the two lower MGN12H mounting holes for the probe itself.
Hence why I grinded a little slope between them to make room, as seen on the image (marked in red).

![image](https://user-images.githubusercontent.com/20250551/148653352-f3479e34-c9f3-4a89-81cd-d7839db9e6c7.png)

**Comment by raymondh2** [comment] 2022-01-08 17:27
Duplicate of #51

**Closed as completed by raymondh2** 2022-01-08 17:27 UTC
