### ISSUE TITLE
blower_housing_rear wire clearance

### ISSUE THREAD

**Issue by geoffrey-young** [VoronDesign/Voron-Afterburner#13] opened 2021-06-07 18:22 UTC
blower_housing_rear doesn't quite have enough clearance for the wires of the BOM (2.4) blower, leaving two options - wires are crushed against the housing, or remove the wires from their clips and risk them coming detached from their solder points.  Both happened to me.

I made a very minor adjustment to the housing that alleviates the issue, which I thought would be good to illustrate

[marked up (master) stl showing location of required fix](https://www.dropbox.com/s/xla9d09jeyvuyxh/blower%20housing%20fix.png?dl=0)
[printed part with fix](https://www.dropbox.com/s/xcgux1s7hpevfm0/blower%20housing%20issue.jpg?dl=0)

Fix available in https://github.com/VoronDesign/Voron-Afterburner/pull/12

**Comment by stvptrsn** [comment] 2021-08-31 01:41
A fix for this was intended to be included in the May update.  I'm not sure why it didn't make it in but I just included it along with several other corrections.  Thanks for pointing it out.

**Closed by stvptrsn** 2021-08-31 01:41 UTC
